Comment CI to test new step

diff --git a/.github/workflows/cpu_tests.yml b/.github/workflows/cpu_tests.yml
--- a/.github/workflows/cpu_tests.yml
+++ b/.github/workflows/cpu_tests.yml
@@ -44,7 +44,7 @@ jobs:
   pre_job:
     name: 'Check for unnecessary runs'
     runs-on: ubuntu-latest
-    if: github.repository == 'gyselax/gyselalibxx' && (github.event_name != 'pull_request' || github.event.pull_request.draft == false)
+    #if: github.repository == 'gyselax/gyselalibxx' && (github.event_name != 'pull_request' || github.event.pull_request.draft == false)
     # Map a step output to a job output
     outputs:
       should_skip: ${{ steps.skip_check.outputs.should_skip }}
@@ -71,99 +71,99 @@ jobs:
           echo "toolchain_matrix=$matrix" >> $GITHUB_OUTPUT
         shell: bash
 
-  docker_update:
-    runs-on: ubuntu-latest
-    outputs:
-      image_tag: ${{ steps.docker.outputs.image_tag }}
-    if: github.repository == 'gyselax/gyselalibxx' && (github.event_name != 'pull_request' || github.event.pull_request.draft == false)
-    steps:
-      - uses: actions/checkout@v4
-      - id: docker
-        uses: ./.github/actions/docker_update
-        with:
-          always_push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
-          # Build the release tag with a ternary expression
-          # 'latest' if push else (release.tag_name if release else '')
-          release_tag: ${{ github.event_name == 'push' && 'latest' || ( github.event_name == 'release' && github.event.release.tag_name || '') }}
+  #docker_update:
+  #  runs-on: ubuntu-latest
+  #  outputs:
+  #    image_tag: ${{ steps.docker.outputs.image_tag }}
+  #  if: github.repository == 'gyselax/gyselalibxx' && (github.event_name != 'pull_request' || github.event.pull_request.draft == false)
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - id: docker
+  #      uses: ./.github/actions/docker_update
+  #      with:
+  #        always_push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
+  #        # Build the release tag with a ternary expression
+  #        # 'latest' if push else (release.tag_name if release else '')
+  #        release_tag: ${{ github.event_name == 'push' && 'latest' || ( github.event_name == 'release' && github.event.release.tag_name || '') }}
 
-  cpu_tests:
-    runs-on: ubuntu-latest
-    needs: [pre_job, docker_update]
-    strategy:
-      matrix:
-        toolchain: ${{fromJson(needs.pre_job.outputs.toolchain_matrix)}}
-        compiler:
-          - name: 'gnu'
-            c_compiler: 'gcc'
-            cxx_compiler: 'g++'
-          - name: 'clang'
-            c_compiler: 'clang'
-            cxx_compiler: 'clang++'
-        exclude:
-          - toolchain: 'ci_coverage_toolchain'
-            compiler:
-              name: 'clang'
-          - toolchain: 'openmp_release_toolchain' # Clang + OpenMP leads to compiler failure with Clang 14.0.0
-            compiler:
-              name: 'clang'
-      fail-fast: false
-    container:
-      image: ${{ needs.docker_update.outputs.image_tag }}
-    name: CPU Test (${{ matrix.toolchain }}, ${{ matrix.compiler.name }})
-    env:
-      CC: ${{ matrix.compiler.c_compiler }}
-      CXX: ${{ matrix.compiler.cxx_compiler }}
-    steps:
-      - name: Checkout gyselalibxx
-        if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - name: "Filter tests"
-        if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
-        uses: ./.github/actions/test_filter
-      - name: Build code
-        if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
-        uses: ./.github/actions/build_code
-        with:
-          toolchain: toolchains/common_toolchains/${{ matrix.toolchain }}.cmake
-      - name: Run tests
-        if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
-        uses: ./.github/actions/run_tests
-      - name: Check Test Coverage
-        if: needs.pre_job.outputs.should_skip == 'false' && matrix.toolchain == 'ci_coverage_toolchain'
-        run: |
-          pip install gcovr
-          gcovr --filter src --lcov coverage.lcov --merge-mode-functions=merge-use-line-0 build
-          # Remove branch information (causes more problems than it fixes)
-          sed '/^BRDA:/d' -i coverage.lcov
-          sed '/^BRH:/d' -i coverage.lcov
-          sed '/^BRF:/d' -i coverage.lcov
-      - name: Archive code coverage results
-        if: needs.pre_job.outputs.should_skip == 'false' && matrix.toolchain == 'ci_coverage_toolchain'
-        uses: actions/upload-artifact@v4
-        with:
-          name: code-coverage-report
-          path: coverage.lcov
+  #cpu_tests:
+  #  runs-on: ubuntu-latest
+  #  needs: [pre_job, docker_update]
+  #  strategy:
+  #    matrix:
+  #      toolchain: ${{fromJson(needs.pre_job.outputs.toolchain_matrix)}}
+  #      compiler:
+  #        - name: 'gnu'
+  #          c_compiler: 'gcc'
+  #          cxx_compiler: 'g++'
+  #        - name: 'clang'
+  #          c_compiler: 'clang'
+  #          cxx_compiler: 'clang++'
+  #      exclude:
+  #        - toolchain: 'ci_coverage_toolchain'
+  #          compiler:
+  #            name: 'clang'
+  #        - toolchain: 'openmp_release_toolchain' # Clang + OpenMP leads to compiler failure with Clang 14.0.0
+  #          compiler:
+  #            name: 'clang'
+  #    fail-fast: false
+  #  container:
+  #    image: ${{ needs.docker_update.outputs.image_tag }}
+  #  name: CPU Test (${{ matrix.toolchain }}, ${{ matrix.compiler.name }})
+  #  env:
+  #    CC: ${{ matrix.compiler.c_compiler }}
+  #    CXX: ${{ matrix.compiler.cxx_compiler }}
+  #  steps:
+  #    - name: Checkout gyselalibxx
+  #      if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
+  #      uses: actions/checkout@v4
+  #      with:
+  #        submodules: recursive
+  #    - name: "Filter tests"
+  #      if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
+  #      uses: ./.github/actions/test_filter
+  #    - name: Build code
+  #      if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
+  #      uses: ./.github/actions/build_code
+  #      with:
+  #        toolchain: toolchains/common_toolchains/${{ matrix.toolchain }}.cmake
+  #    - name: Run tests
+  #      if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
+  #      uses: ./.github/actions/run_tests
+  #    - name: Check Test Coverage
+  #      if: needs.pre_job.outputs.should_skip == 'false' && matrix.toolchain == 'ci_coverage_toolchain'
+  #      run: |
+  #        pip install gcovr
+  #        gcovr --filter src --lcov coverage.lcov --merge-mode-functions=merge-use-line-0 build
+  #        # Remove branch information (causes more problems than it fixes)
+  #        sed '/^BRDA:/d' -i coverage.lcov
+  #        sed '/^BRH:/d' -i coverage.lcov
+  #        sed '/^BRF:/d' -i coverage.lcov
+  #    - name: Archive code coverage results
+  #      if: needs.pre_job.outputs.should_skip == 'false' && matrix.toolchain == 'ci_coverage_toolchain'
+  #      uses: actions/upload-artifact@v4
+  #      with:
+  #        name: code-coverage-report
+  #        path: coverage.lcov
 
-  upload_coverage:
-    name: Coverage upload
-    needs: [pre_job, cpu_tests]
-    runs-on: ubuntu-latest
-    if: (github.event_name != 'workflow_dispatch' || inputs.toolchain == 'ci_coverage_toolchain') && needs.pre_job.outputs.should_skip == 'false'
-    steps:
-      - name: Checkout gyselalibxx
-        uses: actions/checkout@v4
-      - name: Download a single artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: code-coverage-report
-      - name: Upload coverage reports to Codecov with GitHub Action
-        uses: codecov/codecov-action@v5
-        with:
-          files: coverage.lcov
-          token: ${{ secrets.CODECOV_TOKEN }}
-          verbose: true
+  #upload_coverage:
+  #  name: Coverage upload
+  #  needs: [pre_job, cpu_tests]
+  #  runs-on: ubuntu-latest
+  #  if: (github.event_name != 'workflow_dispatch' || inputs.toolchain == 'ci_coverage_toolchain') && needs.pre_job.outputs.should_skip == 'false'
+  #  steps:
+  #    - name: Checkout gyselalibxx
+  #      uses: actions/checkout@v4
+  #    - name: Download a single artifact
+  #      uses: actions/download-artifact@v4
+  #      with:
+  #        name: code-coverage-report
+  #    - name: Upload coverage reports to Codecov with GitHub Action
+  #      uses: codecov/codecov-action@v5
+  #      with:
+  #        files: coverage.lcov
+  #        token: ${{ secrets.CODECOV_TOKEN }}
+  #        verbose: true
 
   include_what_you_use:
     name: Check includes
@@ -171,7 +171,6 @@ jobs:
     needs: docker_update
     container:
       image: ${{ needs.docker_update.outputs.image_tag }}
-      options: --user root
     env:
       CC: 'clang'
       CXX: 'clang++'
@@ -202,15 +201,15 @@ jobs:
           cmake -DCMAKE_TOOLCHAIN_FILE=toolchains/common_toolchains/serial_debug_toolchain.cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE=$(pwd)/include-what-you-use/build/bin/include-what-you-use -B build -S .
         shell: bash
 
-  set_pr_status:
-    runs-on: ubuntu-latest
-    name: CPU PR result
-    needs: [cpu_tests]
-    if: always() && (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
-    steps:
-      - uses: actions/checkout@v4
-      - uses: ./.github/actions/set_pr_status
-        with:
-          status: ${{ needs.cpu_tests.result }}
-          pr_number: ${{ github.event.pull_request.number }}
-          sha: ${{ github.event.pull_request.head.sha || github.sha }}
+  #set_pr_status:
+  #  runs-on: ubuntu-latest
+  #  name: CPU PR result
+  #  needs: [cpu_tests]
+  #  if: always() && (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - uses: ./.github/actions/set_pr_status
+  #      with:
+  #        status: ${{ needs.cpu_tests.result }}
+  #        pr_number: ${{ github.event.pull_request.number }}
+  #        sha: ${{ github.event.pull_request.head.sha || github.sha }}
